import { groq } from 'next-sanity'

export const destinationsQuery = groq`
  *[_type == "destination"] | order(order asc) {
    nameEs,
    nameEn,
    cityId,
    slug,
    image,
    order,
  }
`

export const featuredPropertiesQuery = groq`
  *[_type == "property" && featured == true] | order(featuredOrder asc) {
    nameEs,
    nameEn,
    slug,
    destination,
    images,
    descriptionEs,
    descriptionEn,
    hostifyUrl,
  }
`

export const homePageQuery = groq`
  *[_type == "homePage"][0] {
    heroImage,
    heroTitleEs,
    heroTitleEn,
    heroSubtitleEs,
    heroSubtitleEn,
    heroCtaLabel,
    heroCtaUrl,
    aboutImage,
    aboutTitleEs,
    aboutTitleEn,
    aboutBodyEs,
    aboutBodyEn,
    seoTitleEs,
    seoTitleEn,
    seoDescriptionEs,
    seoDescriptionEn,
    destinationEs,
    destinationEn,
    checkInEs,
    checkInEn,
    checkOutEs,
    checkOutEn,
    guestsEs,
    guestsEn,
    searchEs,
    searchEn,
    destinationsEyebrowEs,
    destinationsEyebrowEn,
    destinationsTitleEs,
    destinationsTitleEn,
    destinationsExploreLabelEs,
    destinationsExploreLabelEn,
    destinationsFooterLabelEs,
    destinationsFooterLabelEn,
    featuredEyebrowEs,
    featuredEyebrowEn,
    featuredReserveLabelEs,
    featuredReserveLabelEn, 
    experienceEyebrowEs,
    experienceEyebrowEn,
    experienceTitleEs,
    experienceTitleEn,
    experienceCells[] {
      _key,
      cellType,
      image,
      titleEs,
      titleEn,
      bodyEs,
      bodyEn,
    },
    ownersBodyEs,
    ownersBodyEn,
    ownersImages,
    ownersImages,
    bookNowLabelEs,
    bookNowLabelEn,
    footerTaglineEs,
    footerTaglineEn,
    footerEmailPrimary,
    footerEmailSecondary,
    footerPhoneArg,
    footerPhoneMex,
    footerWebsite,
    footerSiteArg,
    footerSiteMex,
    footerCopyrightEs,
    footerCopyrightEn,
  }
`